# Basic Application Metadata
spring.application.name=supremeribs

# Datasource Configuration
# Use jdbc:h2:mem:testdb for in-memory or jdbc:h2:file:./data/sample for file-based persistence
spring.datasource.url=jdbc:h2:mem:supremeribsdb
spring.datasource.username=root
spring.datasource.password=+3010Cv465
# The correct H2 driver name is org.h2.Driver
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Optional: Set the H2 Dialect specifically
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console (Required to view the database in a browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MVC Strategy
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
springdoc.swagger-ui.path=/swagger-ui.html